server:
  port: '8081'

spring:
  datasource:
    url: jdbc:mysql://222.119.100.89:3382/demoedu?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: demouser
    password: 1234

  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl_auto: create-drop

  mvc:
    static-path-pattern: /**

  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
      add-mappings: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace